#5 davaleba
print(True or False)
print(False or True)
print(False or False or True)
print(True or True or False)
print(False or False or False)
print(True or True or True)
print(False or False)
print(True or True)
print(False or True or True or True)
print(True and False)
print(False and True)
print(False and False)
print(False and False and False)
print(True and True)
print(True and True and True)
print(True and False and False)
print(True and True and False)
print(False and False and True)
print(False and False and False and False)
print(True and True and True and True)