first=input("name")
second=input("surname")
third=input("age")
fourth=input("Hobi")
fifth=input("name")
six=input("surname")
seven=input("age")
eight=input("hobi")

print(first + second + third + fourth)
print(fifth + six + seven + eight)